### ISSUE TITLE
Containerized osdsdock service doesn't work when calling ceph backend

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds#260]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When I test the opensds cluster using docker-compose tool, it failed when calling ListPools method in ceph driver. And then osdsdock service would crash down because of some unexpected errors:
```
root@ubuntu:~# docker logs 25745df796a0
E0209 02:45:35.278842       1 ceph.go:114] exit status 1
E0209 02:45:35.279239       1 ceph.go:434] [Error]:exit status 1
E0209 02:45:35.279317       1 ceph.go:506] exit status 1
E0209 02:45:35.279360       1 discovery.go:90] Call driver to list pools failed:exit status 1
panic: exit status 1

goroutine 1 [running]:
main.main()
	/root/gopath/src/github.com/opensds/opensds/cmd/osdsdock/osdsdock.go:54 +0x1a0
```

**What you expected to happen**:
Get this bug fixed.

**How to reproduce it (as minimally and precisely as possible)**:

* Install ceph cluster
* Configure opensds variable
* Start containerized opensds service

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version: master
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools: docker-compose
- Others:

**Comment by leonwanghui** [comment]
I have fixed this bug by adding a line in `docker-compose.yml`:
```yml
  osdsdock:
    image: 'opensdsio/opensds-dock:latest'
    tty: true
    network_mode: "host"
    privileged: true
    volumes:
    - /etc/opensds:/etc/opensds
    - /etc/ceph:/etc/ceph
    depends_on:
    - osdsdb
```

Now the osdsdock service could run well, but when I login in the container, It seems that I still can't execute some cpeh shell command like what I did in vms:
```
root@ubuntu:/go# ceph df
2018-02-09 10:03:00.851139 7f82a8503700  0 -- 10.10.3.163:0/1000048 >> 10.10.3.163:6789/0 pipe(0x7f82a4020230 sd=3 :58442 s=1 pgs=0 cs=0 l=1 c=0x7f82a40204c0).connect protocol feature mismatch, my fffffffffff < peer 4010ff8eea4fffb missing 401000000000000
2018-02-09 10:03:00.851551 7f82a8503700  0 -- 10.10.3.163:0/1000048 >> 10.10.3.163:6789/0 pipe(0x7f82a4020230 sd=3 :58442 s=1 pgs=0 cs=0 l=1 c=0x7f82a40204c0).fault
2018-02-09 10:03:00.851948 7f82a8503700  0 -- 10.10.3.163:0/1000048 >> 10.10.3.163:6789/0 pipe(0x7f82a4020230 sd=3 :58444 s=1 pgs=0 cs=0 l=1 c=0x7f82a40204c0).connect protocol feature mismatch, my fffffffffff < peer 4010ff8eea4fffb missing 401000000000000
2018-02-09 10:03:01.052809 7f82a8503700  0 -- 10.10.3.163:0/1000048 >> 10.10.3.163:6789/0 pipe(0x7f82a4020230 sd=3 :58446 s=1 pgs=0 cs=0 l=1 c=0x7f82a40204c0).connect protocol feature mismatch, my fffffffffff < peer 4010ff8eea4fffb missing 401000000000000
2018-02-09 10:03:01.453610 7f82a8503700  0 -- 10.10.3.163:0/1000048 >> 10.10.3.163:6789/0 pipe(0x7f82a4020230 sd=3 :58448 s=1 pgs=0 cs=0 l=1 c=0x7f82a40204c0).connect protocol feature mismatch, my fffffffffff < peer 4010ff8eea4fffb missing 401000000000000
2018-02-09 10:03:02.254504 7f82a8503700  0 -- 10.10.3.163:0/1000048 >> 10.10.3.163:6789/0 pipe(0x7f82a4020230 sd=3 :58450 s=1 pgs=0 cs=0 l=1 c=0x7f82a40204c0).connect protocol feature mismatch, my fffffffffff < peer 4010ff8eea4fffb missing 401000000000000
```

I don't know if it's caused from the machine environment, but I will dive into this issue.

**Comment by xxwjj** [comment]
There is some wrong with the docker base imge kernel version. This [link](http://ceph-users.ceph.narkive.com/kLgFojZi/client-ceph-can-not-connect-from-client-connect-protocol-feature-mismatch) will useful.
