### ISSUE TITLE
Ups Storage Plugin Runtime Error

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds#41]
##  What version of env (opensds, os, golang etc) are you using?
- opensds: master branch
- os: ubuntu 17.04
- golang: go1.7.6 linux/amd64

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## What happened?
When I tried to test the function of whole system, I found that every time I called ups-storage-driver to create volume (attachment and snapshot) resource, the dock process will go crush and print some error info:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x52af2f]

goroutine 26 [running]:
panic(0x89e840, 0xc42000c0f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/opensds/opensds/pkg/dock/api.CreateVolume(0xc4201921e0, 0x2, 0x2, 0x872e60)
	/home/krej/gopath/src/github.com/opensds/opensds/pkg/dock/api/api.go:48 +0x17f
github.com/opensds/opensds/pkg/grpc/dock/server.(*dockServer).CreateVolume(0xc42018e420, 0x7fb1fbbbe120, 0xc420184de0, 0xc4201921e0, 0x0, 0x16b, 0x16b)
	/home/krej/gopath/src/github.com/opensds/opensds/pkg/grpc/dock/server/server.go:70 +0xdb
github.com/opensds/opensds/pkg/grpc/opensds._Dock_CreateVolume_Handler(0x8eb0a0, 0xc42018e420, 0x7fb1fbbbe120, 0xc420184de0, 0xc420664500, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/krej/gopath/src/github.com/opensds/opensds/pkg/grpc/opensds/opensds.pb.go:374 +0x27d
google.golang.org/grpc.(*Server).processUnaryRPC(0xc42018a3c0, 0xb7cca0, 0xc420088840, 0xc42006c300, 0xc420184810, 0xb9f560, 0xc420184e70, 0x0, 0x0)
	/home/krej/gopath/src/google.golang.org/grpc/server.go:781 +0xd14
google.golang.org/grpc.(*Server).handleStream(0xc42018a3c0, 0xb7cca0, 0xc420088840, 0xc42006c300, 0xc420184e70)
	/home/krej/gopath/src/google.golang.org/grpc/server.go:981 +0x7a0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4206666b0, 0xc42018a3c0, 0xb7cca0, 0xc420088840, 0xc42006c300)
	/home/krej/gopath/src/google.golang.org/grpc/server.go:551 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/krej/gopath/src/google.golang.org/grpc/server.go:552 +0xa3
```

After doing some analysis to ups-storage-driver, I found that there is some issues when initializing all structures like this:
```go
func (p *Plugin) CreateVolume(name string, size int64) (*api.VolumeSpec, error) {
	return &api.VolumeSpec{}, nil
}
```

I will pull a request for solving this issue soon later, please take your time to have a review at it. Thanks!

**Comment by leonwanghui** [comment]
Since PR has been submitted and merged, I will close this Issue.
