### ISSUE TITLE
Osdslet process exited abnormally when I deleted a volume in the error state

### ISSUE THREAD

**Issue by imquanquan** [opensds/opensds#737]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:

When I deleted a volume in the error state,the osdslet process exited abnormally.
Contents of `osdslet.err`:

```
E0515 09:40:40.758333   18176 volumecontroller.go:94] create volume failed in volume controller:rpc error: code = Unknown desc = rados: Connection timed out
E0515 09:40:40.758423   18176 controller.go:160] when create volume:rpc error: code = Unknown desc = rados: Connection timed out
E0515 09:42:41.896716   18176 etcd.go:713] When get profile in db:Wrong resource uuid provided!
E0515 09:42:41.897308   18176 etcd.go:1012] When get volume in db:Wrong resource uuid provided!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x9ceb23]

goroutine 6319 [running]:
github.com/opensds/opensds/pkg/db/drivers/etcd.(*Client).UpdateStatus(0xc0002161a0, 0xc00043a200, 0xa5dd40, 0x0, 0xb91905, 0xd, 0xc0003324e0, 0xc00032c5c0)
        /root/workspace/gopath/src/github.com/opensds/opensds/pkg/db/drivers/etcd/etcd.go:2233 +0x5a3
github.com/opensds/opensds/pkg/db.UpdateVolumeStatus(0xc00043a200, 0xc8ca20, 0xc0002161a0, 0xc000282000, 0x24, 0xb91905, 0xd, 0x0, 0xc0008bc2d0)
        /root/workspace/gopath/src/github.com/opensds/opensds/pkg/db/db.go:183 +0xa4
github.com/opensds/opensds/pkg/controller.(*Controller).DeleteVolume(0xc000218230, 0xc7da00, 0xc0008bc2a0, 0xc000242800, 0x0, 0x0, 0x0)
        /root/workspace/gopath/src/github.com/opensds/opensds/pkg/controller/controller.go:192 +0x1de
github.com/opensds/opensds/pkg/model/proto._Controller_DeleteVolume_Handler(0xb5a5a0, 0xc000218230, 0xc7da00, 0xc0008bc2a0, 0xc000218460, 0x0, 0xc7da00, 0xc0008bc2a0, 0xc00001a700, 0x32b)
        /root/workspace/gopath/src/github.com/opensds/opensds/pkg/model/proto/model.pb.go:3065 +0x23e
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fc900, 0xc83cc0, 0xc00052d980, 0xc000462100, 0xc000212660, 0x11a8798, 0x0, 0x0, 0x0)
        /root/workspace/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:966 +0x470
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0001fc900, 0xc83cc0, 0xc00052d980, 0xc000462100, 0x0)
        /root/workspace/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:1245 +0xd25
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00028c620, 0xc0001fc900, 0xc83cc0, 0xc00052d980, 0xc000462100)
        /root/workspace/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:685 +0x9f
created by github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /root/workspace/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:683 +0xa1
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Disconnect the network and create a Volume:

```
osdsctl volume create 1 --name 1
```

Waiting for connection timeout,the volume status changes to error:

```
+--------------------------------------+------+-------------+---------+------+------------------+----------+--------+-----------+
| Id                                   | Name | Description | GroupId | Size | AvailabilityZone | Status   | PoolId | ProfileId |
+--------------------------------------+------+-------------+---------+------+------------------+----------+--------+-----------+
| ebd77a23-e79e-4c70-b6d2-0ec3052ceab6 | 1    |             |         | 1    | default          | error |        |           |
+--------------------------------------+------+-------------+---------+------+------------------+----------+--------+-----------+
```

Delete this volume:

```
osdsctl volume delete  ebd77a23-e79e-4c70-b6d2-0ec3052ceab6
```

View osdslet status:

```
ps aux | grep osdslet
```

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:v0.5.1
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Can you explain which version you are using?

**Comment by imquanquan** [comment]
**Environment**:
- Hotpot(release/branch) version: Capri release v0.5.1
- OS (e.g. from /etc/os-release): Debian 9
- Kernel (e.g. `uname -a`): 3.16.0-6-amd64

![image](https://user-images.githubusercontent.com/13776945/57744415-ac3c1b80-76fb-11e9-9d0c-c0a94a277e72.png)

**Comment by wisererik** [comment]
Hi @imquanquan the reason of nil error is that osdslet didn't get volume from db with id `ebd77a23-e79e-4c70-b6d2-0ec3052ceab6` and didn't check the return values too. This is an issue. I'm confused about why  osdslet didn't get volume from db. 
can you send the result of following commands:

- osdsctl volume list
- osdsctl profile list

**Comment by imquanquan** [comment]
Hi @wisererik before deleting the volume:

```
root@test5:/opt/opensds-hotpot# osdsctl volume list
+--------------------------------------+------+-------------+---------+------+--------+-----------+
| Id                                   | Name | Description | GroupId | Size | Status | ProfileId |
+--------------------------------------+------+-------------+---------+------+--------+-----------+
| ed777438-6793-4367-9a0b-1f7cd43b891e | 1    |             |         | 1    | error  |           |
+--------------------------------------+------+-------------+---------+------+--------+-----------+
root@test5:/opt/opensds-hotpot# osdsctl profile list
+--------------------------------------+---------+----------------+-------------+
| Id                                   | Name    | Description    | StorageType |
+--------------------------------------+---------+----------------+-------------+
| 333d73bc-6c94-4371-ac56-602864bf5d22 | default | default policy | block       |
+--------------------------------------+---------+----------------+-------------+

```

After deleting the volume:

```
root@cld-test5-10009:/opt/opensds-hotpot# osdsctl volume delete ed777438-6793-4367-9a0b-1f7cd43b891e
[4]+  Exit 2                  nohup /opt/opensds-hotpot/bin/osdslet > osdslet.out 2> osdslet.err < /dev/null
root@cld-test5-10009:/opt/opensds-hotpot# osdsctl volume list
+----+------+-------------+------+--------+-----------+---------+
| Id | Name | Description | Size | Status | ProfileId | GroupId |
+----+------+-------------+------+--------+-----------+---------+
+----+------+-------------+------+--------+-----------+---------+
root@cld-test5-10009:/opt/opensds-hotpot# osdsctl profile list
+--------------------------------------+---------+----------------+-------------+
| Id                                   | Name    | Description    | StorageType |
+--------------------------------------+---------+----------------+-------------+
| 333d73bc-6c94-4371-ac56-602864bf5d22 | default | default policy | block       |
+--------------------------------------+---------+----------------+-------------+
```
osdslet.err
```
E0516 16:42:08.811153    9277 etcd.go:713] When get profile in db:Wrong resource uuid provided!
E0516 16:42:08.811692    9277 etcd.go:1012] When get volume in db:Wrong resource uuid provided!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x9ceb23]

goroutine 78 [running]:
github.com/opensds/opensds/pkg/db/drivers/etcd.(*Client).UpdateStatus(0xc0001c01a0, 0xc00048e000, 0xa5dd40, 0x0, 0xb91905, 0xd, 0xc0001c0640, 0xc000309390)
        /root/workspace/gopath/src/github.com/opensds/opensds/pkg/db/drivers/etcd/etcd.go:2233 +0x5a3
github.com/opensds/opensds/pkg/db.UpdateVolumeStatus(0xc00048e000, 0xc8ca20, 0xc0001c01a0, 0xc0002a61b0, 0x24, 0xb91905, 0xd, 0x0, 0xc0001fe8d0)
        /root/workspace/gopath/src/github.com/opensds/opensds/pkg/db/db.go:183 +0xa4
github.com/opensds/opensds/pkg/controller.(*Controller).DeleteVolume(0xc0000ca2d0, 0xc7da00, 0xc0001fe8a0, 0xc000452600, 0x0, 0x0, 0x0)
        /root/workspace/gopath/src/github.com/opensds/opensds/pkg/controller/controller.go:192 +0x1de
github.com/opensds/opensds/pkg/model/proto._Controller_DeleteVolume_Handler(0xb5a5a0, 0xc0000ca2d0, 0xc7da00, 0xc0001fe8a0, 0xc0002bf450, 0x0, 0xc7da00, 0xc0001fe8a0, 0xc00031ae00, 0x32b)
        /root/workspace/gopath/src/github.com/opensds/opensds/pkg/model/proto/model.pb.go:3065 +0x23e
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000096f00, 0xc83cc0, 0xc000097800, 0xc000316400, 0xc000224660, 0x11a8798, 0x0, 0x0, 0x0)
        /root/workspace/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:966 +0x470
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000096f00, 0xc83cc0, 0xc000097800, 0xc000316400, 0x0)
        /root/workspace/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:1245 +0xd25
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002ac1b0, 0xc000096f00, 0xc83cc0, 0xc000097800, 0xc000316400)
        /root/workspace/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:685 +0x9f
created by github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
```

**Comment by imquanquan** [comment]
This bug will not appear in hotpot v0.5.2,and can only be reproduced in hotpot v0.5.1.

**Comment by leonwanghui** [comment]
I think what you mentioned is a bug we have fixed in v0.5.2, could you upgrade and use the latest v0.5.2?

**Comment by imquanquan** [comment]
Yes, I upgraded the hotpot to v0.5.2 yesterday and found that the bug has been fixed.

**Comment by leonwanghui** [comment]
Cool, if so can you close this issue now?
