### ISSUE TITLE
[dashboard] ACL is not setting properly because of wrong passing parameter

### ISSUE THREAD

**Issue by PravinRanjan10** [opensds/opensds#839]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Two separate string is passed. It should be array of string.

ype:"ip" **accessCapability:"Read" accessCapability:"Write"** accessTo:"10.0.0.0"

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
When I tried to create file share acl using dashboard, there was some errors occurred in Hotpot controller and then `osdslet` was broken. Please see the logs from `osdslet.ERROR` file:
```shell
root@ubuntu:~/gopath/src/github.com/opensds/opensds# ./build/out/bin/osdslet -logtostderr
I0611 23:59:45.828753   14831 logs.go:75] [Info] LogFlushFrequency: 5s
I0611 23:59:45.840819   14831 controller.go:92] Controller server initialized! Start listening on port:[::]:50049
I0612 00:00:01.730634   14831 controller.go:969] controller server receive create file share acl request, vr =id:"e8948243-9a59-40ac-a31f-81bbe04471d7" fileshareId:"270748a8-4284-44c7-89e6-1b0b763957fe" type:"ip" accessCapability:"Read" accessCapability:"Write" accessTo:"10.10.3.150" profile:"{\"id\":\"09de8a13-1872-40df-be46-f1c93eeafcc2\",\"createdAt\":\"2019-06-11T22:53:52\",\"updatedAt\":\"\",\"name\":\"default\",\"description\":\"default policy\",\"storageType\":\"file\",\"provisioningProperties\":{\"dataStorage\":{\"storageAccessCapability\":[\"Read\",\"Write\",\"Execute\"],\"isSpaceEfficient\":false},\"ioConnectivity\":{}},\"replicationProperties\":{\"dataProtection\":{\"isIsolated\":false},\"replicaInfos\":{}},\"snapshotProperties\":{\"schedule\":{},\"retention\":{},\"topology\":{}},\"dataProtectionProperties\":{\"dataProtection\":{\"isIsolated\":false}}}" context:"{\"auth_token\":\"\",\"user_id\":\"558057c4256545bd8a307c37464003c9\",\"tenant_id\":\"94b280022d0c4401bcf3b0ea85870519\",\"domain_id\":\"\",\"user_domain_id\":\"\",\"project_domain_id\":\"\",\"is_admin\":true,\"read_only\":\"\",\"show_deleted\":\"\",\"request_id\":\"\",\"resource_uuid\":\"\",\"overwrite\":\"\",\"roles\":[\"admin\"],\"user_name\":\"\",\"project_name\":\"\",\"domain_name\":\"\",\"user_domain_name\":\"\",\"project_domain_name\":\"\",\"is_admin_project\":true,\"service_token\":\"\",\"service_user_id\":\"\",\"service_user_name\":\"\",\"service_user_domain_id\":\"\",\"service_user_domain_name\":\"\",\"service_project_id\":\"\",\"service_project_name\":\"\",\"service_project_domain_id\":\"\",\"service_project_domain_name\":\"\",\"service_roles\":\"\",\"token\":\"\",\"uri\":\"/v1beta/94b280022d0c4401bcf3b0ea85870519/file/acls\"}" metadata:<key:"lvPath" value:"/dev/opensds-files-default/shr_02" > metadata:<key:"nfsFileshareID" value:"270748a8-4284-44c7-89e6-1b0b763957fe" > metadata:<key:"nfsFileshareName" value:"shr_02" > 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9c972c]

goroutine 34 [running]:
github.com/opensds/opensds/pkg/db/drivers/etcd.(*Client).UpdateFileShareAcl(0xc00017e2c0, 0xc0000fe200, 0xc0002267e0, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/opensds/opensds/pkg/db/drivers/etcd/etcd.go:281 +0x3c
github.com/opensds/opensds/pkg/controller.(*Controller).CreateFileShareAcl(0xc0001545b0, 0xd37bc0, 0xc00013bd40, 0xc00010fba0, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/opensds/opensds/pkg/controller/controller.go:1001 +0xcf4
github.com/opensds/opensds/pkg/model/proto._FileShareController_CreateFileShareAcl_Handler(0xc0f9c0, 0xc0001545b0, 0xd37bc0, 0xc00013bd40, 0xc000182730, 0x0, 0xd37bc0, 0xc00013bd40, 0xc000039200, 0x5d1)
	/root/gopath/src/github.com/opensds/opensds/pkg/model/proto/model.pb.go:5502 +0x23e
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b2000, 0xd3ee20, 0xc0001b2180, 0xc00017a200, 0xc00013b530, 0x12d2180, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:966 +0x470
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0001b2000, 0xd3ee20, 0xc0001b2180, 0xc00017a200, 0x0)
	/root/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:1245 +0xd25
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000037b50, 0xc0001b2000, 0xd3ee20, 0xc0001b2180, 0xc00017a200)
	/root/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:685 +0x9f
created by github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/root/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:683 +0xa1
```

I don't know if the reason is what you mentioned, please take a look.

**Comment by BaiHuoYu** [comment]
Today I tested the latest code. Do you see if it is related to your problem?
osdsctl fileshare acl create 6bf19304-1038-460a-85d6-c76395b49bd9 -t ip -a  "0.0.0.0/0" -c '["read","write"]'
+------------------+--------------------------------------+
| Property         | Value                                |
+------------------+--------------------------------------+
| Id               | 1ce1b768-bd2d-4666-b2f3-0cdcc9e3d998 |
| CreatedAt        | 2019-06-12T10:20:51                  |
| TenantId         | e93b4c0934da416eb9c8d120c5d04d96     |
| FileShareId      | 6bf19304-1038-460a-85d6-c76395b49bd9 |
| Type             | ip                                   |
| AccessCapability | [read write]                         |
| AccessTo         | 0.0.0.0/0                            |
| Description      |                                      |
+------------------+--------------------------------------+

**Comment by skdwriting** [comment]
check PR #842 , test and close.

**Comment by PravinRanjan10** [comment]
Tested!! Able to set the ACL properly
