### ISSUE TITLE
osdslet daemon crashed when creating file share acl

### ISSUE THREAD

**Issue by leonwanghui** [opensds/opensds#841]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When I use opensds dashboard to create a file share and then create the file share acl, the system crashed and `osdslet` service broken leaving the file share acl status to `creating`.

Here is the output log of `osdslet` service:
```shell
root@ubuntu:~/gopath/src/github.com/opensds/opensds# ./build/out/bin/osdslet -logtostderr
I0611 23:59:45.828753   14831 logs.go:75] [Info] LogFlushFrequency: 5s
I0611 23:59:45.840819   14831 controller.go:92] Controller server initialized! Start listening on port:[::]:50049
I0612 00:00:01.730634   14831 controller.go:969] controller server receive create file share acl request, vr =id:"e8948243-9a59-40ac-a31f-81bbe04471d7" fileshareId:"270748a8-4284-44c7-89e6-1b0b763957fe" type:"ip" accessCapability:"Read" accessCapability:"Write" accessTo:"10.10.3.150" profile:"{\"id\":\"09de8a13-1872-40df-be46-f1c93eeafcc2\",\"createdAt\":\"2019-06-11T22:53:52\",\"updatedAt\":\"\",\"name\":\"default\",\"description\":\"default policy\",\"storageType\":\"file\",\"provisioningProperties\":{\"dataStorage\":{\"storageAccessCapability\":[\"Read\",\"Write\",\"Execute\"],\"isSpaceEfficient\":false},\"ioConnectivity\":{}},\"replicationProperties\":{\"dataProtection\":{\"isIsolated\":false},\"replicaInfos\":{}},\"snapshotProperties\":{\"schedule\":{},\"retention\":{},\"topology\":{}},\"dataProtectionProperties\":{\"dataProtection\":{\"isIsolated\":false}}}" context:"{\"auth_token\":\"\",\"user_id\":\"558057c4256545bd8a307c37464003c9\",\"tenant_id\":\"94b280022d0c4401bcf3b0ea85870519\",\"domain_id\":\"\",\"user_domain_id\":\"\",\"project_domain_id\":\"\",\"is_admin\":true,\"read_only\":\"\",\"show_deleted\":\"\",\"request_id\":\"\",\"resource_uuid\":\"\",\"overwrite\":\"\",\"roles\":[\"admin\"],\"user_name\":\"\",\"project_name\":\"\",\"domain_name\":\"\",\"user_domain_name\":\"\",\"project_domain_name\":\"\",\"is_admin_project\":true,\"service_token\":\"\",\"service_user_id\":\"\",\"service_user_name\":\"\",\"service_user_domain_id\":\"\",\"service_user_domain_name\":\"\",\"service_project_id\":\"\",\"service_project_name\":\"\",\"service_project_domain_id\":\"\",\"service_project_domain_name\":\"\",\"service_roles\":\"\",\"token\":\"\",\"uri\":\"/v1beta/94b280022d0c4401bcf3b0ea85870519/file/acls\"}" metadata:<key:"lvPath" value:"/dev/opensds-files-default/shr_02" > metadata:<key:"nfsFileshareID" value:"270748a8-4284-44c7-89e6-1b0b763957fe" > metadata:<key:"nfsFileshareName" value:"shr_02" > 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9c972c]

goroutine 34 [running]:
github.com/opensds/opensds/pkg/db/drivers/etcd.(*Client).UpdateFileShareAcl(0xc00017e2c0, 0xc0000fe200, 0xc0002267e0, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/opensds/opensds/pkg/db/drivers/etcd/etcd.go:281 +0x3c
github.com/opensds/opensds/pkg/controller.(*Controller).CreateFileShareAcl(0xc0001545b0, 0xd37bc0, 0xc00013bd40, 0xc00010fba0, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/opensds/opensds/pkg/controller/controller.go:1001 +0xcf4
github.com/opensds/opensds/pkg/model/proto._FileShareController_CreateFileShareAcl_Handler(0xc0f9c0, 0xc0001545b0, 0xd37bc0, 0xc00013bd40, 0xc000182730, 0x0, 0xd37bc0, 0xc00013bd40, 0xc000039200, 0x5d1)
	/root/gopath/src/github.com/opensds/opensds/pkg/model/proto/model.pb.go:5502 +0x23e
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b2000, 0xd3ee20, 0xc0001b2180, 0xc00017a200, 0xc00013b530, 0x12d2180, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:966 +0x470
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0001b2000, 0xd3ee20, 0xc0001b2180, 0xc00017a200, 0x0)
	/root/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:1245 +0xd25
github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000037b50, 0xc0001b2000, 0xd3ee20, 0xc0001b2180, 0xc00017a200)
	/root/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:685 +0x9f
created by github.com/opensds/opensds/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/root/gopath/src/github.com/opensds/opensds/vendor/google.golang.org/grpc/server.go:683 +0xa1
```

**What you expected to happen**:
Fix this bug.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy opensds cluster and login in opensds dashboard, create a file share and then create a share acl, you will find `osdslet` would be broken.

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version: development
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools: `devsds`
- Others:

**Comment by skdwriting** [comment]
Please test and close this issue and all related issues
